import type { getArticleBySlug } from "./db"

type DbArticle = NonNullable<Awaited<ReturnType<typeof getArticleBySlug>>>

/** Maps a Prisma Article record to the frontend Article interface. */
export function mapArticleToFrontend(article: DbArticle, urlPrefix = "/articles"): Article {
  return {
    _id: article.id,
    headline: article.headline || "",
    alternativeHeadline: article.alternativeHeadline || "",
    excerpt: article.excerpt || "",
    articleBody: article.articleBody || "",
    pageContent: article.pageContent || "",
    diveContent: article.diveContent || "",
    datePublished: article.publishedAt?.toISOString() || "",
    dateCreated: article.createdAt.toISOString(),
    dateModified: article.updatedAt.toISOString(),
    updatedAt: article.updatedAt.toISOString(),
    createdAt: article.createdAt.toISOString(),
    publishedAt: article.publishedAt?.toISOString() || "",
    author: article.author ? [{ id: article.author.id, name: article.author.name || "" }] : [],
    categories: article.categoryRef ? [article.categoryRef.id] : [],
    category: article.categoryRef?.id || article.category || "",
    categoryIsNews: article.categoryRef?.isNews ?? false,
    categorySlug: article.categoryRef?.slug || "",
    newsType: "",
    agency: "",
    ampValidationMessage: "",
    archivedAt: "",
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    contentType: (article.contentType as any) || "articles",
    editor: "",
    expires: "",
    genre: article.genre || [],
    keywords: article.keywords || [],
    language: article.language || "en",
    locationCreated: "",
    mainEntityOfPage: "",
    metaDescription: article.metaDescription || "",
    metaTitle: article.metaTitle || "",
    publisher: "",
    siteId: article.siteId || "",
    sourceType: "",
    subCategories: article.subCategories || [],
    tags: article.tags || [],
    url: `${urlPrefix}/${article.slug}`,
    key: parseInt(article.id.slice(-6), 16),
    isContent: true,
    description: article.excerpt || "",
    name: article.headline || "",
    slug: article.slug || "",
    status: article.status,
    visibility: article.visibility ?? true,
    optionalfield: "",
    images: (article.images || []).map((img) => ({
      imageCategory: img.imageCategory || "",
      imageCategoryValue: img.imageCategoryValue || "",
      imageDescription: img.imageDescription || "",
      imageUrl: img.imageUrl || [],
      key: article.id,
    })),
  }
}
